version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/src
    networks:
      - my_network

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src
    networks:
      - my_network

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
